# coding:utf-8
from enum import Enum


class AppErrorCode(str, Enum):
    TASK_INIT_FAILED = "TASK_INIT_FAILED"
    TASK_EXECUTION_FAILED = "TASK_EXECUTION_FAILED"
    GAME_WINDOW_NOT_FOUND = "GAME_WINDOW_NOT_FOUND"
    CONFIG_MIGRATION_FAILED = "CONFIG_MIGRATION_FAILED"

